### ISSUE TITLE
AspectJ Gradle plugin

### ISSUE THREAD

**Issue by ravitechy** [dev-aspectj/aspectj-maven-plugin#141]
@kriegaex / Team, I am trying to introduce AspectJ to my gradle project, but couldn't do it so far with different plugins available for gradle. May I know if there is a recommended AspectJ plugin that needs to be used for the gradle project?

I am using gradle 8.4 on Java 17

Thanks
Ravi

**Comment by kriegaex** [comment]
This project is, as the name implies, a Maven plugin. And GitHub issues are not for support requests but for bugs or feature requests for that plugin. Please behave. You violated netiquette in multiple ways at once:

1. You abused a bug tracker for a support question.
2. You asked about a totally different tool. Gradle is not Maven.
3. you cross-posted your Stack Overflow question here.
4. Even on Stack Overflow, you hijacked a Maven question instead of searching for Gradle-related questions first and then maybe ask a new one.

Please learn some manners. Like this, you are not going to make friends.
